// <auto-generated />
namespace Echri3endy_Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EditeProduit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditeProduit));
        
        string IMigrationMetadata.Id
        {
            get { return "201801260112134_EditeProduit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
